"""
pair_builder.py — Assemble labelled and unlabelled candidate pairs.

Design intent
-------------
1. Takes blocking candidates and ground truth to assemble labelled training pairs:
   - label = 1: true match according to train_ground_truth.tsv
   - label = 0: hard negative generated by blocking (looks similar, but distinct)
2. Preserves multi-match ground truth (one S1 entity can have 0, 1, or multiple matches).
3. Preserves `source1_entity_id` / `s1_id` explicitly on every row to enable
   entity-level GroupKFold / train-val splitting in Turn 5, preventing data leakage.
4. Joins preprocessed field representations for both S1 and Candidate records.
5. Builds unlabelled pairs for test inference.
"""

from __future__ import annotations

import logging
from typing import Optional

import pandas as pd

from src.evaluation import ground_truth_to_dict
from src.preprocessing import preprocess_records

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Training Pair Builder
# ---------------------------------------------------------------------------


def build_train_pairs(
    source1: pd.DataFrame,
    source2: pd.DataFrame,
    source3: pd.DataFrame,
    candidates: pd.DataFrame,
    ground_truth: pd.DataFrame | dict[str, set[str]],
    sample_neg_ratio: Optional[float] = None,
    random_seed: int = 42,
) -> pd.DataFrame:
    """Build a labelled pair DataFrame for model training.

    Parameters
    ----------
    source1, source2, source3:
        Source DataFrames. (Will be preprocessed if normalized fields are absent).
    candidates:
        Output of :func:`src.blocking.build_candidates` with columns 's1_id', 'candidate_id'.
    ground_truth:
        Either raw ground-truth DataFrame or dict (from `ground_truth_to_dict`).
    sample_neg_ratio:
        Optional float. If specified (e.g. 5.0), limits the ratio of negatives to
        positives per S1 entity to avoid extreme class imbalance. None keeps all.
    random_seed:
        Seed for negative downsampling reproducibility.

    Returns
    -------
    pd.DataFrame with columns:
        s1_id, candidate_id, label (1 or 0),
        s1_name_norm, cand_name_norm,
        s1_name_compact, cand_name_compact,
        s1_name_no_suffix, cand_name_no_suffix,
        s1_address_norm, cand_address_norm,
        s1_country_norm, cand_country_norm,
        s1_script, cand_script,
        s1_is_domain, cand_is_domain,
        s1_domain_stem, cand_domain_stem,
        s1_legal_suffix, cand_legal_suffix,
        cand_source ('S2' or 'S3')
    """
    if candidates is None or len(candidates) == 0:
        return pd.DataFrame(
            columns=["s1_id", "candidate_id", "label", "cand_source"]
        )

    # 1. Parse ground truth mapping
    if isinstance(ground_truth, pd.DataFrame):
        gt_dict = ground_truth_to_dict(ground_truth)
    else:
        gt_dict = ground_truth

    # 2. Ensure preprocessed columns are available
    s1_proc = source1 if "name_norm" in source1.columns else preprocess_records(source1)
    s2_proc = source2 if "name_norm" in source2.columns else preprocess_records(source2)
    s3_proc = source3 if "name_norm" in source3.columns else preprocess_records(source3)

    # Index sources by entity_id for fast O(1) dictionary lookups
    s1_dict = s1_proc.set_index("entity_id").to_dict(orient="index")
    # Combine S2 and S3 into unified candidate dictionary
    cand_dict: dict[str, dict] = {}
    for eid, row in s2_proc.set_index("entity_id").to_dict(orient="index").items():
        cand_dict[str(eid)] = row
    for eid, row in s3_proc.set_index("entity_id").to_dict(orient="index").items():
        cand_dict[str(eid)] = row

    # 3. Label candidate pairs
    pairs_by_s1: dict[str, list[dict]] = {}

    for _, row in candidates.iterrows():
        s1_id = str(row["s1_id"])
        c_id = str(row["candidate_id"])

        s1_rec = s1_dict.get(s1_id)
        c_rec = cand_dict.get(c_id)

        if s1_rec is None or c_rec is None:
            continue

        true_matches = gt_dict.get(s1_id, set())
        is_pos = 1 if c_id in true_matches else 0
        src_tag = "S2" if c_id.startswith("S2") else ("S3" if c_id.startswith("S3") else "other")

        pair_row = {
            "s1_id": s1_id,
            "candidate_id": c_id,
            "label": is_pos,
            "cand_source": src_tag,
            # S1 fields
            "s1_name_norm": s1_rec.get("name_norm"),
            "s1_name_compact": s1_rec.get("name_compact"),
            "s1_name_no_suffix": s1_rec.get("name_no_suffix"),
            "s1_address_norm": s1_rec.get("address_norm"),
            "s1_address_is_missing": s1_rec.get("address_is_missing", False),
            "s1_country_norm": s1_rec.get("country_norm"),
            "s1_script": s1_rec.get("name_script", "unknown"),
            "s1_is_domain": s1_rec.get("is_domain", False),
            "s1_domain_stem": s1_rec.get("domain_stem"),
            "s1_legal_suffix": s1_rec.get("legal_suffix"),
            # Candidate fields
            "cand_name_norm": c_rec.get("name_norm"),
            "cand_name_compact": c_rec.get("name_compact"),
            "cand_name_no_suffix": c_rec.get("name_no_suffix"),
            "cand_address_norm": c_rec.get("address_norm"),
            "cand_address_is_missing": c_rec.get("address_is_missing", False),
            "cand_country_norm": c_rec.get("country_norm"),
            "cand_script": c_rec.get("name_script", "unknown"),
            "cand_is_domain": c_rec.get("is_domain", False),
            "cand_domain_stem": c_rec.get("domain_stem"),
            "cand_legal_suffix": c_rec.get("legal_suffix"),
        }

        if s1_id not in pairs_by_s1:
            pairs_by_s1[s1_id] = []
        pairs_by_s1[s1_id].append(pair_row)

    # 4. Optional Negative Subsampling per S1 Entity
    final_rows: list[dict] = []
    import random

    rng = random.Random(random_seed)

    for s1_id, p_list in pairs_by_s1.items():
        if sample_neg_ratio is None:
            final_rows.extend(p_list)
        else:
            positives = [p for p in p_list if p["label"] == 1]
            negatives = [p for p in p_list if p["label"] == 0]

            # If there are positives, sample negatives proportional to positives
            if positives:
                max_negs = max(1, int(len(positives) * sample_neg_ratio))
                if len(negatives) > max_negs:
                    negatives = rng.sample(negatives, max_negs)
            else:
                # Singleton entity: keep a capped number of hard negatives
                max_negs = int(sample_neg_ratio)
                if len(negatives) > max_negs:
                    negatives = rng.sample(negatives, max_negs)

            final_rows.extend(positives)
            final_rows.extend(negatives)

    pairs_df = pd.DataFrame(final_rows)
    logger.info(
        "Built training pairs: %d total rows (%d positives, %d hard negatives)",
        len(pairs_df),
        (pairs_df["label"] == 1).sum() if len(pairs_df) > 0 else 0,
        (pairs_df["label"] == 0).sum() if len(pairs_df) > 0 else 0,
    )
    return pairs_df


# ---------------------------------------------------------------------------
# Test Pair Builder
# ---------------------------------------------------------------------------


def build_test_pairs(
    source1: pd.DataFrame,
    source2: pd.DataFrame,
    source3: pd.DataFrame,
    candidates: pd.DataFrame,
) -> pd.DataFrame:
    """Build an unlabelled pair DataFrame for test inference.

    Parameters
    ----------
    source1, source2, source3:
        Preprocessed test source DataFrames.
    candidates:
        Output of :func:`src.blocking.build_candidates` on test sources.

    Returns
    -------
    pd.DataFrame with columns matching build_train_pairs, minus 'label'.
    """
    if candidates is None or len(candidates) == 0:
        return pd.DataFrame(columns=["s1_id", "candidate_id", "cand_source"])

    s1_proc = source1 if "name_norm" in source1.columns else preprocess_records(source1)
    s2_proc = source2 if "name_norm" in source2.columns else preprocess_records(source2)
    s3_proc = source3 if "name_norm" in source3.columns else preprocess_records(source3)

    s1_dict = s1_proc.set_index("entity_id").to_dict(orient="index")
    cand_dict: dict[str, dict] = {}
    for eid, row in s2_proc.set_index("entity_id").to_dict(orient="index").items():
        cand_dict[str(eid)] = row
    for eid, row in s3_proc.set_index("entity_id").to_dict(orient="index").items():
        cand_dict[str(eid)] = row

    rows: list[dict] = []
    for _, row in candidates.iterrows():
        s1_id = str(row["s1_id"])
        c_id = str(row["candidate_id"])

        s1_rec = s1_dict.get(s1_id)
        c_rec = cand_dict.get(c_id)

        if s1_rec is None or c_rec is None:
            continue

        src_tag = "S2" if c_id.startswith("S2") else ("S3" if c_id.startswith("S3") else "other")

        rows.append(
            {
                "s1_id": s1_id,
                "candidate_id": c_id,
                "cand_source": src_tag,
                # S1 fields
                "s1_name_norm": s1_rec.get("name_norm"),
                "s1_name_compact": s1_rec.get("name_compact"),
                "s1_name_no_suffix": s1_rec.get("name_no_suffix"),
                "s1_address_norm": s1_rec.get("address_norm"),
                "s1_address_is_missing": s1_rec.get("address_is_missing", False),
                "s1_country_norm": s1_rec.get("country_norm"),
                "s1_script": s1_rec.get("name_script", "unknown"),
                "s1_is_domain": s1_rec.get("is_domain", False),
                "s1_domain_stem": s1_rec.get("domain_stem"),
                "s1_legal_suffix": s1_rec.get("legal_suffix"),
                # Candidate fields
                "cand_name_norm": c_rec.get("name_norm"),
                "cand_name_compact": c_rec.get("name_compact"),
                "cand_name_no_suffix": c_rec.get("name_no_suffix"),
                "cand_address_norm": c_rec.get("address_norm"),
                "cand_address_is_missing": c_rec.get("address_is_missing", False),
                "cand_country_norm": c_rec.get("country_norm"),
                "cand_script": c_rec.get("name_script", "unknown"),
                "cand_is_domain": c_rec.get("is_domain", False),
                "cand_domain_stem": c_rec.get("domain_stem"),
                "cand_legal_suffix": c_rec.get("legal_suffix"),
            }
        )

    return pd.DataFrame(rows)
