"""
threshold.py — Match probability threshold selection and validation tuning.

Design intent
-------------
Optimizes the candidate selection threshold on held-out validation data to
strictly maximize the competition metric: entity-level macro F_0.5 (beta = 0.5).

Key requirements:
1. Purely validation-set tuning: No test data is ever used.
2. Group-aware evaluation: Evaluates macro F_0.5 over all validation Source 1 entities,
   including:
   - Entities with multiple matches
   - Singletons (true match set is empty)
   - Entities where zero candidates were generated by blocking
3. Produces both pair-level and entity-level diagnostics for model comparison.
"""

from __future__ import annotations

import logging
from typing import Any, Iterable, Optional

import numpy as np
import pandas as pd
from sklearn.metrics import (
    average_precision_score,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)

from src.evaluation import entity_f05, ground_truth_to_dict, macro_f05
from src.prediction import predict_matches

logger = logging.getLogger(__name__)


def evaluate_at_threshold(
    pairs: pd.DataFrame,
    proba: np.ndarray,
    threshold: float,
    ground_truth: dict[str, set[str]] | pd.DataFrame,
) -> dict[str, float]:
    """Calculate comprehensive entity-level and pair-level metrics at a fixed threshold.

    Parameters
    ----------
    pairs:
        Validation candidate pairs DataFrame with 's1_id', 'candidate_id',
        and optional 'label'.
    proba:
        Match probabilities from model.
    threshold:
        Decision threshold in [0.0, 1.0].
    ground_truth:
        Validation ground truth mapping.

    Returns
    -------
    dict with metrics:
        macro_f05, non_singleton_f05, singleton_accuracy,
        pair_precision, pair_recall, pair_f1, pr_auc, roc_auc
    """
    if isinstance(ground_truth, pd.DataFrame):
        gt_dict = ground_truth_to_dict(ground_truth)
    else:
        gt_dict = ground_truth

    # 1. Entity-level predictions across all validation entities
    predictions = predict_matches(
        pairs, proba, threshold=threshold, s1_entities=gt_dict.keys()
    )

    # 2. Overall entity-level macro F0.5
    overall_macro = macro_f05(gt_dict, predictions)

    # 3. Separate singleton and non-singleton performance
    singletons = [eid for eid, matches in gt_dict.items() if len(matches) == 0]
    non_singletons = [eid for eid, matches in gt_dict.items() if len(matches) > 0]

    if singletons:
        # Singleton accuracy: proportion where predicted set is also empty
        singleton_correct = sum(
            1 for eid in singletons if len(predictions.get(eid, set())) == 0
        )
        singleton_acc = singleton_correct / len(singletons)
    else:
        singleton_acc = 1.0

    if non_singletons:
        non_sing_total = sum(
            entity_f05(gt_dict[eid], predictions.get(eid, set()))
            for eid in non_singletons
        )
        non_singleton_macro = non_sing_total / len(non_singletons)
    else:
        non_singleton_macro = overall_macro

    # Calculate entity-level precision and recall averages
    from src.evaluation import entity_precision, entity_recall

    total_entity_prec = 0.0
    total_entity_rec = 0.0
    num_fp_entities = 0
    num_fn_entities = 0

    for eid, true_set in gt_dict.items():
        pred_set = predictions.get(eid, set())
        total_entity_prec += entity_precision(true_set, pred_set)
        total_entity_rec += entity_recall(true_set, pred_set)
        if len(pred_set - true_set) > 0:
            num_fp_entities += 1
        if len(true_set - pred_set) > 0:
            num_fn_entities += 1

    n_entities = len(gt_dict) or 1
    mean_entity_prec = total_entity_prec / n_entities
    mean_entity_rec = total_entity_rec / n_entities

    # 4. Pair-level metrics (if binary label exists in pairs)
    metrics: dict[str, float] = {
        "threshold": float(threshold),
        "macro_f05": float(overall_macro),
        "mean_entity_precision": float(mean_entity_prec),
        "mean_entity_recall": float(mean_entity_rec),
        "singleton_accuracy": float(singleton_acc),
        "non_singleton_macro_f05": float(non_singleton_macro),
        "num_val_entities": len(gt_dict),
        "num_singletons": len(singletons),
        "num_non_singletons": len(non_singletons),
        "num_fp_entities": int(num_fp_entities),
        "num_fn_entities": int(num_fn_entities),
    }

    if "label" in pairs.columns and len(pairs) > 0:
        y_true = np.asarray(pairs["label"], dtype=int)
        y_pred = (np.asarray(proba) >= threshold).astype(int)

        metrics["pair_precision"] = float(
            precision_score(y_true, y_pred, zero_division=0)
        )
        metrics["pair_recall"] = float(
            recall_score(y_true, y_pred, zero_division=0)
        )
        metrics["pair_f1"] = float(
            f1_score(y_true, y_pred, zero_division=0)
        )

        try:
            metrics["pr_auc"] = float(average_precision_score(y_true, proba))
        except Exception:
            metrics["pr_auc"] = 0.0

        try:
            metrics["roc_auc"] = float(roc_auc_score(y_true, proba))
        except Exception:
            metrics["roc_auc"] = 0.0
    else:
        metrics["pair_precision"] = 0.0
        metrics["pair_recall"] = 0.0
        metrics["pair_f1"] = 0.0
        metrics["pr_auc"] = 0.0
        metrics["roc_auc"] = 0.0

    return metrics


def find_optimal_threshold(
    pairs: pd.DataFrame,
    proba: np.ndarray,
    ground_truth: dict[str, set[str]] | pd.DataFrame,
    threshold_grid: Optional[Iterable[float]] = None,
    beta: float = 0.5,
) -> tuple[float, float, dict[float, float]]:
    """Search for the decision threshold that maximizes validation entity-level macro F_0.5.

    Parameters
    ----------
    pairs:
        Validation candidate pairs DataFrame with 's1_id' and 'candidate_id'.
    proba:
        1D array of match probabilities from the model.
    ground_truth:
        Validation ground truth mapping (dict or DataFrame).
    threshold_grid:
        Collection of candidate thresholds to test in [0.0, 1.0].
        Defaults to 19 points: 0.05 to 0.95 with step 0.05.
    beta:
        Beta parameter for F_beta (default 0.5).

    Returns
    -------
    best_threshold:
        Threshold that achieves the highest macro F_0.5 on the validation set.
    best_macro_f05:
        Validation macro F_0.5 score at best_threshold.
    sweep_history:
        Mapping: threshold -> macro F_0.5.
    """
    if threshold_grid is None:
        grid = np.linspace(0.05, 0.95, 19).tolist()
    else:
        grid = [float(t) for t in threshold_grid]

    if isinstance(ground_truth, pd.DataFrame):
        gt_dict = ground_truth_to_dict(ground_truth)
    else:
        gt_dict = ground_truth

    sweep_history: dict[float, float] = {}
    best_threshold: float = 0.50
    best_macro_f05: float = -1.0

    for thresh in grid:
        metrics = evaluate_at_threshold(pairs, proba, thresh, gt_dict)
        score = metrics["macro_f05"]
        sweep_history[thresh] = score

        if score > best_macro_f05:
            best_macro_f05 = score
            best_threshold = thresh

    logger.info(
        "Optimal validation threshold: %.2f (Macro F0.5 = %.4f)",
        best_threshold,
        best_macro_f05,
    )

    return best_threshold, best_macro_f05, sweep_history
